package com.Illuninance

// list import classes
import com.arduinotron.model.Devices;
import com.arduinotron.model.ServerEvent;

// default dialect for the semantic code will be MVEL
dialect "mvel"

rule "event=allEvents Rule"
    when
        $event : ServerEvent( $eventId : id, event == "allEvents" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.action = "allEvents"; 
		$device.status = "Light " + $event.getLight();
		com.arduinotron.ui.MainWindow.getInstance().log("Rule event=allEvents: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		modify( $device );
end

rule "keypress1.0 Rule"
    when
        $event : ServerEvent( $eventId : id, event == "keypress1.0" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.action = "keypress1.0"; 
		$device.status = "Light " + $event.getLight();
		com.arduinotron.ui.MainWindow.getInstance().log("Rule keypress1.0: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		modify( $device );
end

rule "keypress2.0 Rule"
    when
        $event : ServerEvent( $eventId : id, event == "keypress2.0" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.action = "keypress2.0"; 
		$device.status = "Light " + $event.getLight();
		com.arduinotron.ui.MainWindow.getInstance().log("Rule keypress2.0: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		modify( $device );
end

rule "reedRelay / Proximity Rule"
    when
        $event : ServerEvent( $eventId : id, (event == "keypress4.0" || event == "keypress8.0") )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.action = "Alert"; 
		$device.status = "Light " + $event.getLight();
		com.arduinotron.ui.MainWindow.getInstance().log("Rule reedRelay / Proximity: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		modify( $device );
end

//declare any rules to fire in the jBPM AI_IoT.Illuminance process
rule "Rule for device ID: 1"
	ruleflow-group "Illuminance Rule Flow"
	when
		$event : ServerEvent( $eventId : id, $eventId == "1" )
	then
		com.arduinotron.ui.MainWindow.getInstance().log("ruleflow-group device ID: 1 " + $event.getEvent() + " - " + $event.getName());
end

rule "Rule for device ID: 2"
	ruleflow-group "Illuminance Rule Flow"
	when
		$event : ServerEvent( $eventId : id, $eventId == "2" )
	then
		com.arduinotron.ui.MainWindow.getInstance().log("ruleflow-group device ID: 2 " + $event.getEvent() + " - " + $event.getName());
end
